name: update

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - uses: actions/checkout@v2

    - name: Setup
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv --python python3.8 sync
        pipenv run python3 update-csv.py --output-file covid19-aut.csv
